sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '4'
  - iojs-v3
  - iojs-v2
  - iojs-v1
  - '0.12'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
