sudo: false
language: node_js
cache:
  directories:
  - node_modules
  - packages/cerebral/node_modules
  - packages/cerebral-forms/node_modules
  - packages/cerebral-provider-http/node_modules
  - packages/cerebral-router/node_modules
  - packages/function-tree/node_modules
notifications:
  email: false
node_js:
- '6'
- '4'
before_install:
- npm i -g npm@^3.0.0
- lerna bootstrap --scope function-tree
- lerna bootstrap --scope cerebral
- lerna bootstrap --scope cerebral-forms
- lerna bootstrap --scope cerebral-provider-http
- lerna bootstrap --scope cerebral-router
before_script:
- npm prune
after_success:
- npm run coverage
- npm run coverage:upload
- |
  echo $TRAVIS_BRANCH; echo $TRAVIS_PULL_REQUEST; echo $TRAVIS_NODE_VERSION; if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_NODE_VERSION == '6' ]]; then
    echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/.npmrc ;
    lerna bootstrap
    lerna publish -c --npm-tag next --yes ;
    git config --global user.email "cerebraljs@gmail.com" ;
    git config --global user.name "Cerebral JS" ;
    npm run deploy;
  fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: YEHzzJgE4Wes6qE0X4dkiwz/mYVqvPfbhcejQ9YbVuORLl62pc6iSpbhWpROYu64BAZRwDygQnY++ggHdWORIpvnQFUpKZ+U/YeMnSXvXLPE5sphAVGzyqJRltw+3T0jyZ+8ksRtGVvSrv8C05wcdVOTodKvToEZyfBBD6ifImGJnBYZYgA+Wt9fqSdF/kjDr0/uAboAhX4atEhGd3BWnnWbNoCxV6fCRcWUlJ88q9lmltBEe8n3DO9E1T7xYVh8e/a/n7Gx6sfNbBFcRcLjIqCUQCd6bvvj9r81FYUtzdkzHXUBnODl1qr0/p+psJMTb5GOAybpFMIx2iBcI944rGVJ8C8QVwwgq+CvEFzwgngOcA7RGsvCgP5f2krrre3hvQdJ+Q2+PSzgd3bewmGuKBrM3ZxSgGC5grt2iyfRYUi/N5URBpP2GEcZX/yG8jqB2/GJFKVmDjndspCACnkhggEkYoqpDa7UdXMed7pBorWs+YI2txMu373llXqO4uPzJLGVkV8glwNSY+2JFdlOzzTjQ9HqDUqIVJRrorKUFiRSBe/teWQMfQKOKt4pjA9Hw0VATPhq9jpE8S5z0oFrl3zKFlUMfGyn+zWCOj152tdOPbQiN+EhlJmrcYbDwgFCScEhBIlim3xBC4533yCxbOdXeH/Z5SURwtKD/xlP6Ls=
  file: package.json
  on:
    repo: cerebral/cerebral
